// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package queries

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const AddPrize = `-- name: AddPrize :batchone
INSERT INTO prizes (year, category)
VALUES ($1, $2)
RETURNING id, year, category, updated_at
`

type AddPrizeBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddPrizeParams struct {
	Year     int32
	Category string
}

func (q *Queries) AddPrize(ctx context.Context, arg []AddPrizeParams) *AddPrizeBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Year,
			a.Category,
		}
		batch.Queue(AddPrize, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddPrizeBatchResults{br, len(arg), false}
}

func (b *AddPrizeBatchResults) QueryRow(f func(int, Prize, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Prize
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Year,
			&i.Category,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *AddPrizeBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const CreateLaureate = `-- name: CreateLaureate :batchone
INSERT INTO laureates (id, firstname, surname, motivation, share)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, firstname, surname, motivation, share, updated_at
`

type CreateLaureateBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateLaureateParams struct {
	ID         int32
	Firstname  string
	Surname    pgtype.Text
	Motivation string
	Share      int32
}

func (q *Queries) CreateLaureate(ctx context.Context, arg []CreateLaureateParams) *CreateLaureateBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Firstname,
			a.Surname,
			a.Motivation,
			a.Share,
		}
		batch.Queue(CreateLaureate, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateLaureateBatchResults{br, len(arg), false}
}

func (b *CreateLaureateBatchResults) QueryRow(f func(int, Laureate, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Laureate
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Firstname,
			&i.Surname,
			&i.Motivation,
			&i.Share,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateLaureateBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const LinkLaureateToPrize = `-- name: LinkLaureateToPrize :batchexec
INSERT INTO prizes_to_laureates (prize_id, laureate_id)
VALUES ($1, $2)
`

type LinkLaureateToPrizeBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type LinkLaureateToPrizeParams struct {
	PrizeID    int32
	LaureateID int32
}

func (q *Queries) LinkLaureateToPrize(ctx context.Context, arg []LinkLaureateToPrizeParams) *LinkLaureateToPrizeBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PrizeID,
			a.LaureateID,
		}
		batch.Queue(LinkLaureateToPrize, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &LinkLaureateToPrizeBatchResults{br, len(arg), false}
}

func (b *LinkLaureateToPrizeBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *LinkLaureateToPrizeBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
