// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: laureates.sql

package queries

import (
	"context"
)

const GetLaureate = `-- name: GetLaureate :one
SELECT id, firstname, surname, motivation, share FROM laureates
         WHERE id = $1
`

func (q *Queries) GetLaureate(ctx context.Context, id int32) (Laureate, error) {
	row := q.db.QueryRow(ctx, GetLaureate, id)
	var i Laureate
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Surname,
		&i.Motivation,
		&i.Share,
	)
	return i, err
}

const ListLaureates = `-- name: ListLaureates :many
SELECT id, firstname, surname, motivation, share FROM laureates
            ORDER BY id
`

func (q *Queries) ListLaureates(ctx context.Context) ([]Laureate, error) {
	rows, err := q.db.Query(ctx, ListLaureates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Laureate
	for rows.Next() {
		var i Laureate
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Surname,
			&i.Motivation,
			&i.Share,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
