// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Laureate struct {
	ID         int32
	Firstname  string
	Surname    pgtype.Text
	Motivation string
	Share      int32
}

type Prize struct {
	ID       int32
	Year     int32
	Category string
}

type PrizesToLaureate struct {
	PrizeID    int32
	LaureateID int32
}
