// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prizes.sql

package queries

import (
	"context"
)

const PrizesList = `-- name: PrizesList :many
SELECT
  prizes.id, prizes.year, prizes.category,
  COALESCE(
    jsonb_agg(to_jsonb(laureates) ORDER BY laureates.id) FILTER (WHERE laureates.id IS NOT NULL),
    '[]'
  ) AS laureates
FROM prizes
LEFT JOIN laureates ON laureates.id = prizes.laureate_id
GROUP BY prizes.id
ORDER BY prizes.id
`

type PrizesListRow struct {
	ID        int32
	Year      int32
	Category  string
	Laureates interface{}
}

func (q *Queries) PrizesList(ctx context.Context) ([]PrizesListRow, error) {
	rows, err := q.db.Query(ctx, PrizesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrizesListRow
	for rows.Next() {
		var i PrizesListRow
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Category,
			&i.Laureates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
