// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package queries

import (
	"context"
)

const GetLastUpdate = `-- name: GetLastUpdate :one
SELECT 
  COALESCE(
    GREATEST(
      (SELECT MAX(updated_at) FROM laureates),
      (SELECT MAX(updated_at) FROM prizes)
    ),
    NOW()
  ) as last_update
`

func (q *Queries) GetLastUpdate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, GetLastUpdate)
	var last_update interface{}
	err := row.Scan(&last_update)
	return last_update, err
}

const GetStats = `-- name: GetStats :one
SELECT 
  (SELECT COUNT(*) FROM laureates) as laureates_count,
  (SELECT COUNT(*) FROM prizes) as prizes_count,
  (SELECT COUNT(DISTINCT category) FROM prizes) as categories_count
`

type GetStatsRow struct {
	LaureatesCount  int64
	PrizesCount     int64
	CategoriesCount int64
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, GetStats)
	var i GetStatsRow
	err := row.Scan(&i.LaureatesCount, &i.PrizesCount, &i.CategoriesCount)
	return i, err
}
